### ISSUE TITLE
Exception in _on_connection_change when dispatching blitzortung_mqtt_connected

### ISSUE THREAD

**Issue by codyc1515** [mrk-its/homeassistant-blitzortung#68] opened 2022-12-03 00:11 UTC
Receiving an error in the latest beta version of HA (core-2022.12.0b1).

```
Logger: homeassistant.util.logging
Source: util/logging.py:168 
First occurred: 1:05:25 PM (1 occurrences) 
Last logged: 1:05:25 PM

Exception in _on_connection_change when dispatching 'blitzortung_mqtt_connected': () Traceback (most recent call last): File "/config/custom_components/blitzortung/__init__.py", line 213, in _on_connection_change sensor.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 659, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1482, in async_set self._bus.async_fire( File "/usr/src/homeassistant/homeassistant/core.py", line 933, in async_fire self._hass.async_add_hass_job(job, event) File "/usr/src/homeassistant/homeassistant/core.py", line 484, in async_add_hass_job self.loop.call_soon(hassjob.target, *args) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 752, in call_soon self._check_thread() File "/usr/local/lib/python3.10/asyncio/base_events.py", line 789, in _check_thread raise RuntimeError( RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
```

**Comment by codyc1515** [comment] 2022-12-04 22:53
Any update on this? The plug-in will stop working completely in 2022.12 unless this is fixed.

**Comment by harfordhawk** [comment] 2023-01-04 19:36
I guess it quit working, at least for me.

**Comment by mrk-its** [comment] 2023-01-15 14:51
@codyc1515 I cannot reproduce it on Home Assistant 2023.1.4 - it looks everything works as before for me.
Any hints how to reproduce it?

**Comment by harfordhawk** [comment] 2023-01-15 16:55
seems to be working again as far as i can tell

**Comment by mrk-its** [comment] 2023-01-15 17:04
so closing it for now, let's reopen / create new one if problem appear again

**Closed by mrk-its** 2023-01-15 17:04 UTC
