### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by bieniu** [mrk-its/homeassistant-blitzortung#18] opened 2020-09-25 06:52 UTC
Yesterday there were such errors in my log:
```
2020-09-24 19:37:22 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_52_144201_19_438226
2020-09-24 20:37:27 WARNING (MainThread) [homeassistant.helpers.dispatcher] Unable to remove unknown dispatcher <bound method BlitzortungEvent._delete_callback of <Entity Lightning Strike: 34.5>>
2020-09-24 20:37:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 529, in async_remove
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity geo_location.lightning_strike_52_144201_19_438226 async_remove called twice
```

**Comment by mrk-its** [comment] 2020-09-25 09:23
Thanks for report, closing as duplicate of #17

**Closed by mrk-its** 2020-09-25 09:23 UTC

**Comment by bieniu** [comment] 2020-09-25 09:25
Ups, sorry, I'm blind 🤦

**Comment by zibous** [comment] 2022-06-28 06:25
Same problem here (version v1.1.2) via Hacs:

```
2022-06-27 18:07:50 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_a8fe424490ff69c2baa3cbf3d93fdd4e8f3d6ef1
2022-06-27 18:07:57 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_1a10fc281feca2ecda56acaf03579369b0428b6b
2022-06-27 18:07:58 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_48b3354a3407512bf92d1441276c73869579745f
2022-06-27 18:07:58 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_be842ffc35d4bb5e09ab863c72c7816ef3dd389f
2022-06-27 18:08:16 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_13299fc7783f9c04d12daeb816f9d8d73861528b
2022-06-27 18:08:20 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_bb6ec288cb90b4d820310426f7aa5a4a2c971c1c
2022-06-27 18:08:20 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_db561fb47e59072ce7b94eab53ab5ed2b2eeada9
2022-06-27 18:08:20 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_a9558fc70ded9770075ee2fd41154a591ccacce3
2022-06-27 18:08:20 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_887574b86a67441b552b1e8df9f67304e254a200
2022-06-27 18:08:20 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_d8aef9cc4578db7ae3e534febb44ca6903e6d9fd
2022-06-27 18:08:26 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_16c0572bd46ac27c2aaec1917f0fa2119ba59b4e
2022-06-27 18:08:27 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_56079f8d851726296efa3f64d56080761bab3399
2022-06-27 18:08:27 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_6ca28f1bf808c6848d3f83354ba839a760ccc30d
2022-06-27 18:08:27 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_c3287bf059e6f82cef66179931068995757eff1d
2022-06-27 18:08:28 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_c3ac09ca4bfac4848976640a438dc4c0b2362422
2022-06-27 18:08:28 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_a2893d116353311b4f74e69d5bd0e90686a968b4
2022-06-27 18:08:28 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_f4f599998ac3cc240452bffe5e86f22efac2e316
2022-06-27 18:08:28 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_c622f2cc611989da3865f098e4d4eaa654bb70ab
2022-06-27 18:08:29 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_881d1c0d5e72bb42b78700f995a6eb1bf1938bc1
2022-06-27 18:09:02 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_673dcf6f0ecba1d067ab4b50a96246817813bad8
2022-06-27 18:09:02 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_5de5e507055ea66557043ecae658bd21a233bc50
2022-06-27 18:09:02 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_072ac129fb0d1fb531ede7715bfbee5c238dc5cf
2022-06-27 18:09:02 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_6e6a083281f8d41593e109ab74ebf8498a6acb0f
2022-06-27 18:09:03 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_ad1ba1bb8dcf1fdb4d29bd7a55daf326c249cb1c
2022-06-27 18:09:38 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_074d3562a887c57484114087ad04c765ae49bac0
2022-06-27 18:09:39 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_f1a5e2c738ae4f34f59fef30a96f7d288d237be1
2022-06-27 18:09:39 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_9f41de75baeca39cdf8edc9ce4ee0120d9fdd240
2022-06-27 18:09:49 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_aa8eacb002917cd6ffd189f57b7ab6e2fb09231a
```
